### Shop Owners
GET http://localhost:3000/shop_owners

### Stores
GET http://localhost:3000/localhost:3000/stores

### Products
GET http://localhost:3000/products

###  Add New Product
POST http://localhost:3000/add_product
Content-Type: application/json

{
    "name": "Teclado Mecânico",
    "description": "It's for typing stuff",
    "category": "eletronics",
    "status": true,
    "price": 20,
    "compareAtPrice": 30,
    "images": ["kkk.jpeg", "kakaka.png"]
}

### Create new account 
POST http://localhost:3000/new_owner
Content-Type: application/json

{
    "owner_username": "Caique Sarkis",
    "owner_password": "33416738aA!"
}


### Login
POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "Caique Sarkis",
    "password": "33416738aA!"
}

### Logout
POST http://localhost:3000/logout

### Create Store
POST http://localhost:3000/add_store
Content-Type: application/json

{
    "store_name": "Mechdevil"
}
