GET http://localhost:3000/products/?caique=5

### 
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Teclado Mecânico",
    "description": "It's for typing stuff",
    "category": "eletronics",
    "status": true,
    "price": 20,
    "compareAtPrice": 30,
    "images": ["kkk.jpeg", "kakaka.png"]
}

### 
POST http://localhost:3000/stores
Content-Type: application/json

{
    "Store_Name": "Mechdevil",
    "Owner": "Caique Sarkis"
}
